export const words = [
  "about", "account", "across", "addition", "after", "again", "against", "agreement",
  "algorithm", "allocation", "altitude", "amplifier", "analog", "analysis", "anatomy",
  "angle", "angular", "anonymous", "antibody", "application", "archive", "argument",
  "array", "artificial", "assignment", "asynchronous", "atmosphere", "authentication",
  "automatic", "autonomous", "backup", "bandwidth", "binary", "biosphere", "biotechnology",
  "bit", "blockchain", "boolean", "botnet", "browser", "buffer", "bug", "byte", "cache",
  "calculus", "calibration", "capacitor", "carbon", "cellular", "ceramic", "charge",
  "chemical", "chromosome", "circuit", "climate", "cloud", "coefficient", "collision",
  "compiler", "complex", "compression", "conductor", "connection", "constant",
  "contamination", "control", "convection", "coordinate", "corrosion", "cosmic",
  "cryptography", "cybersecurity", "database", "debugging", "decryption", "decomposition",
  "default", "defragmentation", "density", "derivative", "diagnostics", "diffusion",
  "digital", "dimension", "discrete", "disk", "domain", "dosage", "drone", "dynamic",
  "ecosystem", "elasticity", "electric", "electromagnetism", "element", "emission",
  "encryption", "energy", "entropy", "equation", "equilibrium", "evolution",
  "execution", "exoplanet", "experiment", "fiber", "file", "firmware", "fluid",
  "force", "formula", "friction", "frequency", "fossil", "function", "fusion",
  "galaxy", "gas", "gene", "genetic", "geology", "geophysics", "glacier", "gravity",
  "hashing", "heuristic", "hologram", "host", "HTML", "hydraulic", "hydrology",
  "hyperlink", "hypothesis", "icon", "identifier", "ignition", "impact", "index",
  "induction", "infrared", "inorganic", "input", "interface", "Internet", "ion",
  "isotope", "iteration", "JPEG", "jQuery", "kernel", "kinematics", "kinetic",
  "latency", "laser", "latitude", "layer", "LED", "leverage", "lifespan", "limestone",
  "liquid", "logarithm", "logic", "luminescence", "magnetism", "malware", "mapping",
  "mass", "matter", "mechanics", "memory", "metadata", "metallurgy", "meteorology",
  "microchip", "microscope", "molecule", "momentum", "motion", "multithreading",
  "mutation", "nanotechnology", "natural", "neutron", "network", "nucleus",
  "nylon", "object", "observatory", "oceanography", "optics", "orbit", "organism",
  "oscillation", "output", "oxidation", "parallel", "parameter", "particle",
  "password", "pendulum", "permeability", "photon", "physics", "pixel", "plasma",
  "plastic", "pollution", "polymer", "power", "precipitation", "pressure",
  "processor", "protocol", "pulsar", "quantum", "quark", "radiation", "radioactive",
  "random", "reaction", "receptor", "recycling", "refraction", "relativity",
  "renewable", "resistance", "resolution", "resonance", "robot", "robotics",
  "satellite", "scalar", "science", "semiconductor", "server", "signal",
  "silicon", "simulation", "software", "solar", "solution", "spectrum",
  "speed", "statistic", "storage", "substance", "superconductor",
  "sustainability", "symmetric", "synchronization", "syntax",
  "telescope", "temperature", "terminal", "thermodynamics", "threshold",
  "topology", "toxic", "trajectory", "transistor", "transmission", "troposphere",
  "turbulence", "ultraviolet", "universe", "vaccine", "variable", "vector",
  "velocity", "vibration", "virus", "viscosity", "voltage", "vulnerability",
  "wave", "wavelength", "weather", "web", "wind", "wireless", "X-ray",
  "yield", "zero", "zip"
];
